# Site settings
title: Home
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://seungin-lyu.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Seungin Lyu
user_description: I am a software engineer with a substantial interest in design, community technology, and data science.


user_title: Software Developer
email: seungin.lyu@students.olin.edu
github_username:  SeunginLyu
linkedin_username: www.linkedin.com/in/seungin-lyu
resume_link: https://drive.google.com/file/d/14LnhHQ7U8QJlfP4LiS3YBTIYyh2cn_wc/view?usp=sharing

# Google-analytics
google-analytics:
  id: "UA-104920130-2"

exclude: ['package.json', 'src' , 'node_modules']
