# Site settings
title: Home
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://seungin-lyu.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Seungin Lyu
user_description: I am a software engineer with a substantial interest in design, community technology, and data science.

# Google-analytics
google-analytics:
  id: "UA-104920130-2"

exclude: ['package.json', 'src' , 'node_modules']
